@startuml
title Access Materials Activity Diagram
|Student|
start
:View Course;
:Click "Study Materials;
|System|
:List Available Materials;
|Student|
:Select Material;
|System|
:Download or View Material;

stop
@enduml
