@startuml
title Check Grades Sequence Diagram
autonumber

actor "Student" as Student
participant "Web Client" as Client
participant "Student" as StudentClass
participant "Term" as Term
database "Database" as Database

Student -> Client: View Grades
activate Client
Client -> StudentClass: getGrades(studentId)
activate StudentClass
StudentClass -> Term: findMany()
activate Term
Term -> Database: SELECT * FROM Grade...
activate Database
Database --> Term: Grades[]
deactivate Database
Term --> StudentClass: Grades[]
deactivate Term
StudentClass --> Client: Grades[]
deactivate StudentClass
Client --> Student: Display Grades
deactivate Client

@enduml
