@startuml
title Manage Assignments Sequence Diagram
autonumber

actor "Teacher" as Teacher
participant "Web Client" as Client
participant "Teacher" as TeacherClass
participant "Assignment" as Assignment
database "Database" as Database

Teacher -> Client: Create Assignment
activate Client
Client -> TeacherClass: createAssignment(data)
activate TeacherClass
TeacherClass -> Assignment: create({ data })
activate Assignment
Assignment -> Database: INSERT INTO Assignment...
activate Database
Database --> Assignment: Assignment
deactivate Database
Assignment --> TeacherClass: Assignment
deactivate Assignment
TeacherClass --> Client: Success
Client --> Teacher: Assignment Created
deactivate TeacherClass
deactivate Client

@enduml
