@startuml
title Manage Classes Sequence Diagram
autonumber

actor "Admin" as Admin
participant "Web Client" as Client
participant "Admin" as AdminClass
participant "Class" as Class
database "Database" as Database

' View Classes Flow
Admin -> Client: View Classes List
activate Client
Client -> AdminClass: getClasses()
activate AdminClass
AdminClass -> Class: findMany()
activate Class
Class -> Database: SELECT * FROM Class...
activate Database
Database --> Class: Class[]
deactivate Database
Class --> AdminClass: Class[]
deactivate Class
AdminClass --> Client: Class[]
deactivate AdminClass
Client --> Admin: Display List of Classes
deactivate Client

' User Action Choices
alt Create Class
    Admin -> Client: Click "Add Class"
    activate Client
    Client --> Admin: Display Create Form
    deactivate Client

    Admin -> Client: Fill Details & Submit
    activate Client
    note right of Admin: Name, Grade, Homeroom Teacher

    Client -> AdminClass: createClass(data)
    activate AdminClass
    AdminClass -> AdminClass: Validate Data
    activate AdminClass
    deactivate AdminClass

    opt Validation Pass
        AdminClass -> Class: create({ data })
        activate Class
        Class -> Database: INSERT INTO Class...
        activate Database
        Database --> Class: Created Class
        deactivate Database
        Class --> AdminClass: Class Object
        deactivate Class
        AdminClass --> Client: Success Response
        Client --> Admin: Show Success & Refresh List
    else Validation Fail
        AdminClass --> Client: Error Response
        Client --> Admin: Show Error Message
    end
    deactivate AdminClass
    deactivate Client

else Edit Class
    Admin -> Client: Click "Edit" on Class
    activate Client
    Client -> AdminClass: getClass(id)
    activate AdminClass
    AdminClass -> Class: findUnique({ where: { id } })
    activate Class
    Class -> Database: SELECT * FROM Class...
    activate Database
    Database --> Class: Class Data
    deactivate Database
    Class --> AdminClass: Class Data
    deactivate Class
    AdminClass --> Client: Class Data
    deactivate AdminClass
    Client --> Admin: Display Edit Form with Data
    deactivate Client

    Admin -> Client: Update Details & Submit
    activate Client
    Client -> AdminClass: updateClass(id, data)
    activate AdminClass
    AdminClass -> AdminClass: Validate Data
    activate AdminClass
    deactivate AdminClass

    opt Validation Pass
        AdminClass -> Class: update({ where: { id }, data })
        activate Class
        Class -> Database: UPDATE Class...
        activate Database
        Database --> Class: Updated Class
        deactivate Database
        Class --> AdminClass: Class Object
        deactivate Class
        AdminClass --> Client: Success Response
        Client --> Admin: Show Success & Refresh List
    else Validation Fail
        AdminClass --> Client: Error Response
        Client --> Admin: Show Error Message
    end
    deactivate AdminClass
    deactivate Client

else Delete Class
    Admin -> Client: Click "Delete" on Class
    activate Client
    Client --> Admin: Confirm Deletion?
    deactivate Client
    
    Admin -> Client: Confirm Yes
    activate Client
    Client -> AdminClass: deleteClass(id)
    activate AdminClass
    AdminClass -> Class: delete({ where: { id } })
    activate Class
    Class -> Database: DELETE FROM Class...
    activate Database
    Database --> Class: Success
    deactivate Database
    Class --> AdminClass: Success
    deactivate Class
    AdminClass --> Client: Success Response
    deactivate AdminClass
    Client --> Admin: Show Success & Refresh List
    deactivate Client
end

@enduml
