@startuml
title Submit Assignment Sequence Diagram
autonumber

actor "Student" as Student
participant "Web Client" as Client
participant "Student" as StudentClass
participant "Submission" as Submission
database "Database" as Database

Student -> Client: View Assignment Details
activate Client
Student -> Client: Upload Submission
activate Client
Client -> StudentClass: submitAssignment(assignmentId, file)
activate StudentClass
StudentClass -> StudentClass: Upload File
activate StudentClass
deactivate StudentClass
StudentClass -> Submission: create({ data: { submission } })
activate Submission
Submission -> Database: INSERT INTO Submission...
activate Database
Database --> Submission: Success
deactivate Database
Submission --> StudentClass: Success
deactivate Submission
StudentClass --> Client: Success
Client --> Student: Submitted Successfully
deactivate StudentClass
deactivate Client
deactivate Client

@enduml
